// Generated by tools/gen_resources.py from UDB Properties/Resources.resx: image resources loaded from embedded files.
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Reflection;

namespace CodeImp.DoomBuilder.ThreeDFloorMode.Properties
{
	internal static class Resources
	{
		private static Bitmap Load(string file)
		{
			string name = "CodeImp.DoomBuilder.ThreeDFloorMode.Resources." + file;
			using (Stream s = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
			{
				if (s == null) throw new FileNotFoundException("Embedded resource not found: " + name);
				return (Bitmap)Image.FromStream(s);
			}
		}

		public static Bitmap Ceiling => Load("Ceiling.png");
		// The two toolbar icons that the UDB keeps in MenusForm.resx instead of Resources.resx
		public static Bitmap UpdateSlopes => Load("UpdateSlopes.png");
		public static Bitmap RelocateControlSectors => Load("RelocateControlSectors.png");
		public static Bitmap Floor => Load("Floor.png");
		public static Bitmap FloorAndCeiling => Load("FloorAndCeiling.png");

		/// <summary>Resource name (as in Properties.Resources.Name) to the embedded file under CodeImp.DoomBuilder.Resources.</summary>
		public static readonly Dictionary<string, string> Files = new Dictionary<string, string>(StringComparer.Ordinal)
		{
			["Ceiling"] = "Ceiling.png",
			["Floor"] = "Floor.png",
			["FloorAndCeiling"] = "FloorAndCeiling.png",
		};
	}
}
