// Generated by tools/gen_resources.py from UDB Properties/Resources.resx: image resources loaded from embedded files.
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Reflection;

namespace CodeImp.DoomBuilder.TagExplorer.Properties
{
	internal static class Resources
	{
		private static Bitmap Load(string file)
		{
			string name = "CodeImp.DoomBuilder.TagExplorer.Resources." + file;
			using (Stream s = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
			{
				if (s == null) throw new FileNotFoundException("Embedded resource not found: " + name);
				return (Bitmap)Image.FromStream(s);
			}
		}

		public static Bitmap SearchClear => Load("SearchClear.png");
		public static Bitmap Save => Load("Save.png");
		// The tree icons: UDB keeps them in the ImageList of TagExplorer.resx instead of Resources.resx
		public static Bitmap ThingsGroup => Load("ThingsGroup.png");
		public static Bitmap Things => Load("Things.png");
		public static Bitmap SectorsGroup => Load("SectorsGroup.png");
		public static Bitmap Sectors => Load("Sectors.png");
		public static Bitmap LinesGroup => Load("LinesGroup.png");
		public static Bitmap Lines => Load("Lines.png");

		/// <summary>Resource name (as in Properties.Resources.Name) to the embedded file under CodeImp.DoomBuilder.Resources.</summary>
		public static readonly Dictionary<string, string> Files = new Dictionary<string, string>(StringComparer.Ordinal)
		{
			["SearchClear"] = "SearchClear.png",
			["Save"] = "Save.png",
			["ThingsGroup"] = "ThingsGroup.png",
			["Things"] = "Things.png",
			["SectorsGroup"] = "SectorsGroup.png",
			["Sectors"] = "Sectors.png",
			["LinesGroup"] = "LinesGroup.png",
			["Lines"] = "Lines.png",
		};
	}
}
