// Generated by tools/gen_resources.py from UDB Properties/Resources.resx: image resources loaded from embedded files.
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Reflection;

namespace CodeImp.DoomBuilder.BuilderEffects.Properties
{
	internal static class Resources
	{
		private static Bitmap Load(string file)
		{
			string name = "CodeImp.DoomBuilder.BuilderEffects.Resources." + file;
			using (Stream s = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
			{
				if (s == null) throw new FileNotFoundException("Embedded resource not found: " + name);
				return (Bitmap)Image.FromStream(s);
			}
		}

		public static Bitmap Jitter => Load("Jitter.png");
		public static Bitmap Terrain => Load("Terrain.png");
		public static Bitmap Folder => Load("Folder.png");
		public static Bitmap Update => Load("Update.png");
		public static Bitmap FlatShading => Load("FlatShading.png");

		/// <summary>Resource name (as in Properties.Resources.Name) to the embedded file under CodeImp.DoomBuilder.Resources.</summary>
		public static readonly Dictionary<string, string> Files = new Dictionary<string, string>(StringComparer.Ordinal)
		{
			["Jitter"] = "Jitter.png",
			["Terrain"] = "Terrain.png",
			["Folder"] = "Folder.png",
			["Update"] = "Update.png",
			["FlatShading"] = "FlatShading.png",
		};
	}
}
