// Generated by tools/gen_resources.py from UDB Properties/Resources.resx: image resources loaded from embedded files.
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Reflection;

namespace CodeImp.DoomBuilder.BuilderModes.Properties
{
	internal static class Resources
	{
		private static Bitmap Load(string file)
		{
			string name = "CodeImp.DoomBuilder.BuilderModes.Resources." + file;
			using (Stream s = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
			{
				if (s == null) throw new FileNotFoundException("Embedded resource not found: " + name);
				return (Bitmap)Image.FromStream(s);
			}
		}

		public static Bitmap FloorAlign => Load("FloorAlign.png");
		public static Bitmap CeilsGradient => Load("CeilsGradient.png");
		public static Bitmap ColorPick => Load("ColorPick.png");
		public static Bitmap FilterThings => Load("FilterThings.png");
		public static Bitmap AlignThings => Load("AlignThings.png");
		public static Bitmap QuarterCircleTopLeft => Load("QuarterCircleTopLeft.png");
		public static Bitmap HideAll => Load("HideAll.png");
		public static Bitmap LightRadius => Load("LightRadius.png");
		public static Bitmap CurveLines => Load("CurveLines.png");
		public static Bitmap ThingPointAtCursor => Load("ThingPointAtCursor.png");
		public static Bitmap DrawCurveMode => Load("DrawCurveMode.png");
		public static Bitmap FlipSelectionH => Load("FlipSelectionH.png");
		public static Bitmap Show2 => Load("Show2.png");
		public static Bitmap BrightnessGradient => Load("BrightnessGradient.png");
		public static Bitmap List => Load("List.png");
		public static Bitmap Folder => Load("Folder.png");
		public static Bitmap DrawRectangleMode => Load("DrawRectangleMode.png");
		public static Bitmap Flip => Load("Flip.png");
		public static Bitmap Copy => Load("Copy.png");
		public static Bitmap Merge => Load("Merge.png");
		public static Bitmap treeview => Load("treeview.png");
		public static Bitmap FloorsGradient => Load("FloorsGradient.png");
		public static Bitmap DrawEllipseMode => Load("DrawEllipseMode.png");
		public static Bitmap PasteProperties => Load("PasteProperties.png");
		public static Bitmap Reset => Load("Reset.png");
		public static Bitmap FlipSelectionV => Load("FlipSelectionV.png");
		public static Bitmap Guidelines => Load("Guidelines.png");
		public static Bitmap Radial => Load("Radial.png");
		public static Bitmap DrawGridMode => Load("DrawGridMode.png");
		public static Bitmap PlaceThings => Load("PlaceThings.png");
		public static Bitmap Repeat => Load("Repeat.png");
		public static Bitmap PastePropertiesOptions => Load("PastePropertiesOptions.png");
		public static Bitmap CopyProperties => Load("CopyProperties.png");
		public static Bitmap Door => Load("Door.png");
		public static Bitmap Hide => Load("Hide.png");
		public static Bitmap NewSector2 => Load("NewSector2.png");
		public static Bitmap DrawGeometryMode => Load("DrawGeometryMode.png");
		public static Bitmap SelectThingsInSectors => Load("SelectThingsInSectors.png");
		public static Bitmap Join => Load("Join.png");
		public static Bitmap ViewSelectionIndex => Load("ViewSelectionIndex.png");
		public static Bitmap ViewSelectionEffects => Load("ViewSelectionEffects.png");
		public static Bitmap Text => Load("Text.png");
		public static Bitmap Close => Load("Close.png");
		public static Bitmap SelectTouching => Load("SelectTouching.png");
		public static Bitmap Save => Load("Save.png");
		public static Bitmap Check => Load("Check.png");
		public static Bitmap SoundRadius => Load("SoundRadius.png");
		public static Bitmap List_Images => Load("List_Images.png");
		public static Bitmap Show => Load("Show.png");
		public static Bitmap TextureLock3Dfloor => Load("TextureLock3Dfloor.png");
		public static Bitmap Similar => Load("Similar.png");
		public static Bitmap Angle => Load("Angle.png");
		public static Bitmap CeilingAlign => Load("CeilingAlign.png");
		public static Bitmap HalfCircle => Load("HalfCircle.png");
		public static Bitmap Show3 => Load("Show3.png");
		public static Bitmap TextureLock => Load("TextureLock.png");
		public static Bitmap QuarterCircleTopRight => Load("QuarterCircleTopRight.png");
		public static Bitmap VisualMode => Load("VisualMode.png");
		public static Bitmap Warning => Load("Warning.png");

		/// <summary>Resource name (as in Properties.Resources.Name) to the embedded file under CodeImp.DoomBuilder.Resources.</summary>
		public static readonly Dictionary<string, string> Files = new Dictionary<string, string>(StringComparer.Ordinal)
		{
			["FloorAlign"] = "FloorAlign.png",
			["CeilsGradient"] = "CeilsGradient.png",
			["ColorPick"] = "ColorPick.png",
			["FilterThings"] = "FilterThings.png",
			["AlignThings"] = "AlignThings.png",
			["QuarterCircleTopLeft"] = "QuarterCircleTopLeft.png",
			["HideAll"] = "HideAll.png",
			["LightRadius"] = "LightRadius.png",
			["CurveLines"] = "CurveLines.png",
			["ThingPointAtCursor"] = "ThingPointAtCursor.png",
			["DrawCurveMode"] = "DrawCurveMode.png",
			["FlipSelectionH"] = "FlipSelectionH.png",
			["Show2"] = "Show2.png",
			["BrightnessGradient"] = "BrightnessGradient.png",
			["List"] = "List.png",
			["Folder"] = "Folder.png",
			["DrawRectangleMode"] = "DrawRectangleMode.png",
			["Flip"] = "Flip.png",
			["Copy"] = "Copy.png",
			["Merge"] = "Merge.png",
			["treeview"] = "treeview.png",
			["FloorsGradient"] = "FloorsGradient.png",
			["DrawEllipseMode"] = "DrawEllipseMode.png",
			["PasteProperties"] = "PasteProperties.png",
			["Reset"] = "Reset.png",
			["FlipSelectionV"] = "FlipSelectionV.png",
			["Guidelines"] = "Guidelines.png",
			["Radial"] = "Radial.png",
			["DrawGridMode"] = "DrawGridMode.png",
			["PlaceThings"] = "PlaceThings.png",
			["Repeat"] = "Repeat.png",
			["PastePropertiesOptions"] = "PastePropertiesOptions.png",
			["CopyProperties"] = "CopyProperties.png",
			["Door"] = "Door.png",
			["Hide"] = "Hide.png",
			["NewSector2"] = "NewSector2.png",
			["DrawGeometryMode"] = "DrawGeometryMode.png",
			["SelectThingsInSectors"] = "SelectThingsInSectors.png",
			["Join"] = "Join.png",
			["ViewSelectionIndex"] = "ViewSelectionIndex.png",
			["ViewSelectionEffects"] = "ViewSelectionEffects.png",
			["Text"] = "Text.png",
			["Close"] = "Close.png",
			["SelectTouching"] = "SelectTouching.png",
			["Save"] = "Save.png",
			["Check"] = "Check.png",
			["SoundRadius"] = "SoundRadius.png",
			["List_Images"] = "List_Images.png",
			["Show"] = "Show.png",
			["TextureLock3Dfloor"] = "TextureLock3Dfloor.png",
			["Similar"] = "Similar.png",
			["Angle"] = "Angle.png",
			["CeilingAlign"] = "CeilingAlign.png",
			["HalfCircle"] = "HalfCircle.png",
			["Show3"] = "Show3.png",
			["TextureLock"] = "TextureLock.png",
			["QuarterCircleTopRight"] = "QuarterCircleTopRight.png",
			["VisualMode"] = "VisualMode.png",
			["Warning"] = "Warning.png",
		};
	}
}
