// Generated by tools/port_toolstrip_ui.py from UDB's CurveLinedefsOptionsPanel.Designer.cs: the toolbar items of the panel as Core item objects.
using System;
using System.Windows.Forms;
using CodeImp.DoomBuilder.Controls;

namespace CodeImp.DoomBuilder.BuilderModes.Interface
{
	public partial class CurveLinedefsOptionsPanel
	{
		private System.Windows.Forms.ToolStrip toolstrip;
		private System.Windows.Forms.ToolStripLabel vertslabel;
		private CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown verts;
		private System.Windows.Forms.ToolStripLabel distancelabel;
		private CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown distance;
		private System.Windows.Forms.ToolStripLabel anglelabel;
		private CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown angle;
		private System.Windows.Forms.ToolStripButton flip;
		private System.Windows.Forms.ToolStripButton reset;
		private System.Windows.Forms.ToolStripSeparator separator1;
		private System.Windows.Forms.ToolStripButton fixedcurve;
		private System.Windows.Forms.ToolStripSeparator separator2;
		private System.Windows.Forms.ToolStripButton apply;
		private System.Windows.Forms.ToolStripButton cancel;

		private void InitializeComponent()
		{
			this.toolstrip = new System.Windows.Forms.ToolStrip();
			this.vertslabel = new System.Windows.Forms.ToolStripLabel();
			this.verts = new CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown();
			this.distancelabel = new System.Windows.Forms.ToolStripLabel();
			this.distance = new CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown();
			this.anglelabel = new System.Windows.Forms.ToolStripLabel();
			this.angle = new CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown();
			this.flip = new System.Windows.Forms.ToolStripButton();
			this.reset = new System.Windows.Forms.ToolStripButton();
			this.separator1 = new System.Windows.Forms.ToolStripSeparator();
			this.fixedcurve = new System.Windows.Forms.ToolStripButton();
			this.separator2 = new System.Windows.Forms.ToolStripSeparator();
			this.apply = new System.Windows.Forms.ToolStripButton();
			this.cancel = new System.Windows.Forms.ToolStripButton();
			this.toolstrip.Name = "toolstrip";
			this.toolstrip.Text = "toolStrip1";
			this.vertslabel.Name = "vertslabel";
			this.vertslabel.Text = "Vertices: ";
			this.verts.Increment = 1m;
			this.verts.Maximum = 200m;
			this.verts.Minimum = 1m;
			this.verts.Name = "verts";
			this.verts.Text = "8";
			this.verts.Value = 8m;
			this.distancelabel.Name = "distancelabel";
			this.distancelabel.Text = "Distance:";
			this.distance.Increment = 8m;
			this.distance.Maximum = 10000m;
			this.distance.Minimum = -10000m;
			this.distance.Name = "distance";
			this.distance.Text = "128";
			this.distance.Value = 128m;
			this.anglelabel.Name = "anglelabel";
			this.anglelabel.Text = "Angle:";
			this.angle.Increment = 5m;
			this.angle.Maximum = 350m;
			this.angle.Minimum = 0m;
			this.angle.Name = "angle";
			this.angle.Text = "180";
			this.angle.Value = 180m;
			this.flip.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.flip.Name = "flip";
			this.flip.Text = "Flip Curve";
			this.flip.Image = Properties.Resources.Flip;
			this.reset.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.reset.Name = "reset";
			this.reset.Text = "Reset";
			this.reset.Image = Properties.Resources.Reset;
			this.separator1.Name = "separator1";
			this.fixedcurve.CheckOnClick = true;
			this.fixedcurve.Name = "fixedcurve";
			this.fixedcurve.Text = "Fixed circular curve";
			this.fixedcurve.Image = Properties.Resources.DrawCurveMode;
			this.separator2.Name = "separator2";
			this.apply.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.apply.Name = "apply";
			this.apply.Text = "Apply";
			this.apply.Image = Properties.Resources.Check;
			this.cancel.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.cancel.Name = "cancel";
			this.cancel.Text = "Cancel";
			this.cancel.Image = Properties.Resources.Close;
			this.toolstrip.Items.Add(this.vertslabel);
			this.toolstrip.Items.Add(this.verts);
			this.toolstrip.Items.Add(this.distancelabel);
			this.toolstrip.Items.Add(this.distance);
			this.toolstrip.Items.Add(this.anglelabel);
			this.toolstrip.Items.Add(this.angle);
			this.toolstrip.Items.Add(this.flip);
			this.toolstrip.Items.Add(this.reset);
			this.toolstrip.Items.Add(this.separator1);
			this.toolstrip.Items.Add(this.fixedcurve);
			this.toolstrip.Items.Add(this.separator2);
			this.toolstrip.Items.Add(this.cancel);
			this.toolstrip.Items.Add(this.apply);
			this.verts.ValueChanged += this.OnUIValuesChanged;
			this.distance.ValueChanged += this.OnUIValuesChanged;
			this.angle.ValueChanged += this.OnUIValuesChanged;
			this.flip.Click += this.flip_Click;
			this.reset.Click += this.reset_Click;
			this.fixedcurve.CheckedChanged += this.fixedcurve_CheckedChanged;
			this.apply.Click += this.apply_Click;
			this.cancel.Click += this.cancel_Click;
		}
	}
}
