// Generated by tools/port_toolstrip_ui.py from UDB's DrawCurveOptionsPanel.Designer.cs: the toolbar items of the panel as Core item objects.
using System;
using System.Windows.Forms;
using CodeImp.DoomBuilder.Controls;

namespace CodeImp.DoomBuilder.BuilderModes
{
	internal partial class DrawCurveOptionsPanel
	{
		private System.Windows.Forms.ToolStrip toolstrip;
		private System.Windows.Forms.ToolStripButton continuousdrawing;
		private System.Windows.Forms.ToolStripButton autoclosedrawing;
		private System.Windows.Forms.ToolStripButton placethingsatvertices;
		private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
		private System.Windows.Forms.ToolStripLabel seglabel;
		private CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown seglen;
		private System.Windows.Forms.ToolStripButton reset;

		private void InitializeComponent()
		{
			this.toolstrip = new System.Windows.Forms.ToolStrip();
			this.continuousdrawing = new System.Windows.Forms.ToolStripButton();
			this.autoclosedrawing = new System.Windows.Forms.ToolStripButton();
			this.placethingsatvertices = new System.Windows.Forms.ToolStripButton();
			this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.seglabel = new System.Windows.Forms.ToolStripLabel();
			this.seglen = new CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown();
			this.reset = new System.Windows.Forms.ToolStripButton();
			this.toolstrip.Name = "toolstrip";
			this.toolstrip.Text = "toolStrip1";
			this.continuousdrawing.CheckOnClick = true;
			this.continuousdrawing.Name = "continuousdrawing";
			this.continuousdrawing.Text = "Continuous drawing";
			this.continuousdrawing.Image = Properties.Resources.Repeat;
			this.autoclosedrawing.CheckOnClick = true;
			this.autoclosedrawing.Name = "autoclosedrawing";
			this.autoclosedrawing.Text = "Auto-close drawing";
			this.autoclosedrawing.Image = Properties.Resources.NewSector2;
			this.placethingsatvertices.CheckOnClick = true;
			this.placethingsatvertices.Name = "placethingsatvertices";
			this.placethingsatvertices.Text = "Place things";
			this.placethingsatvertices.Image = Properties.Resources.PlaceThings;
			this.toolStripSeparator1.Name = "toolStripSeparator1";
			this.seglabel.Name = "seglabel";
			this.seglabel.Text = "Segment Length:";
			this.seglen.Maximum = 100m;
			this.seglen.Minimum = 0m;
			this.seglen.Name = "seglen";
			this.seglen.Text = "0";
			this.seglen.Value = 0m;
			this.reset.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.reset.Name = "reset";
			this.reset.Text = "Reset";
			this.reset.Image = Properties.Resources.Reset;
			this.toolstrip.Items.Add(this.continuousdrawing);
			this.toolstrip.Items.Add(this.autoclosedrawing);
			this.toolstrip.Items.Add(this.placethingsatvertices);
			this.toolstrip.Items.Add(this.toolStripSeparator1);
			this.toolstrip.Items.Add(this.seglabel);
			this.toolstrip.Items.Add(this.seglen);
			this.toolstrip.Items.Add(this.reset);
			this.continuousdrawing.CheckedChanged += this.continuousdrawing_CheckedChanged;
			this.autoclosedrawing.CheckedChanged += this.autoclosedrawing_CheckedChanged;
			this.placethingsatvertices.CheckedChanged += this.placethingsatvertices_CheckedChanged;
			this.seglen.ValueChanged += this.seglen_ValueChanged;
			this.reset.Click += this.reset_Click;
		}
	}
}
