// Generated by tools/port_toolstrip_ui.py from UDB's DrawEllipseOptionsPanel.Designer.cs: the toolbar items of the panel as Core item objects.
using System;
using System.Windows.Forms;
using CodeImp.DoomBuilder.Controls;

namespace CodeImp.DoomBuilder.BuilderModes
{
	internal partial class DrawEllipseOptionsPanel
	{
		private System.Windows.Forms.ToolStrip toolStrip1;
		private System.Windows.Forms.ToolStripButton continuousdrawing;
		private System.Windows.Forms.ToolStripButton radialdrawing;
		private System.Windows.Forms.ToolStripButton placethingsatvertices;
		private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
		private System.Windows.Forms.ToolStripLabel subdivslabel;
		private CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown subdivs;
		private System.Windows.Forms.ToolStripLabel spikinesslabel;
		private CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown spikiness;
		private System.Windows.Forms.ToolStripLabel anglelabel;
		private CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown angle;
		private System.Windows.Forms.ToolStripButton reset;
		private System.Windows.Forms.ToolStripButton showguidelines;

		private void InitializeComponent()
		{
			this.toolStrip1 = new System.Windows.Forms.ToolStrip();
			this.continuousdrawing = new System.Windows.Forms.ToolStripButton();
			this.radialdrawing = new System.Windows.Forms.ToolStripButton();
			this.placethingsatvertices = new System.Windows.Forms.ToolStripButton();
			this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.subdivslabel = new System.Windows.Forms.ToolStripLabel();
			this.subdivs = new CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown();
			this.spikinesslabel = new System.Windows.Forms.ToolStripLabel();
			this.spikiness = new CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown();
			this.anglelabel = new System.Windows.Forms.ToolStripLabel();
			this.angle = new CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown();
			this.reset = new System.Windows.Forms.ToolStripButton();
			this.showguidelines = new System.Windows.Forms.ToolStripButton();
			this.toolStrip1.Name = "toolStrip1";
			this.toolStrip1.Text = "toolStrip1";
			this.continuousdrawing.CheckOnClick = true;
			this.continuousdrawing.Name = "continuousdrawing";
			this.continuousdrawing.Text = "Continuous drawing";
			this.continuousdrawing.Image = Properties.Resources.Repeat;
			this.radialdrawing.CheckOnClick = true;
			this.radialdrawing.Name = "radialdrawing";
			this.radialdrawing.Text = "Radial drawing";
			this.radialdrawing.Image = Properties.Resources.Radial;
			this.placethingsatvertices.CheckOnClick = true;
			this.placethingsatvertices.Name = "placethingsatvertices";
			this.placethingsatvertices.Text = "Place things";
			this.placethingsatvertices.Image = Properties.Resources.PlaceThings;
			this.toolStripSeparator1.Name = "toolStripSeparator1";
			this.subdivslabel.Name = "subdivslabel";
			this.subdivslabel.Text = "Sides:";
			this.subdivs.Maximum = 100m;
			this.subdivs.Minimum = 0m;
			this.subdivs.Name = "subdivs";
			this.subdivs.Text = "0";
			this.subdivs.Value = 0m;
			this.spikinesslabel.Name = "spikinesslabel";
			this.spikinesslabel.Text = "Spikiness:";
			this.spikiness.Maximum = 100m;
			this.spikiness.Minimum = 0m;
			this.spikiness.Name = "spikiness";
			this.spikiness.Text = "0";
			this.spikiness.Value = 0m;
			this.anglelabel.Name = "anglelabel";
			this.anglelabel.Text = "Angle:";
			this.angle.Maximum = 360m;
			this.angle.Minimum = -360m;
			this.angle.Name = "angle";
			this.angle.Text = "0";
			this.angle.Value = 0m;
			this.reset.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.reset.Name = "reset";
			this.reset.Text = "Reset";
			this.reset.Image = Properties.Resources.Reset;
			this.showguidelines.CheckOnClick = true;
			this.showguidelines.Name = "showguidelines";
			this.showguidelines.Text = "Guidelines";
			this.showguidelines.Image = Properties.Resources.Guidelines;
			this.toolStrip1.Items.Add(this.continuousdrawing);
			this.toolStrip1.Items.Add(this.showguidelines);
			this.toolStrip1.Items.Add(this.radialdrawing);
			this.toolStrip1.Items.Add(this.placethingsatvertices);
			this.toolStrip1.Items.Add(this.toolStripSeparator1);
			this.toolStrip1.Items.Add(this.subdivslabel);
			this.toolStrip1.Items.Add(this.subdivs);
			this.toolStrip1.Items.Add(this.spikinesslabel);
			this.toolStrip1.Items.Add(this.spikiness);
			this.toolStrip1.Items.Add(this.anglelabel);
			this.toolStrip1.Items.Add(this.angle);
			this.toolStrip1.Items.Add(this.reset);
			this.continuousdrawing.CheckedChanged += this.continuousdrawing_CheckedChanged;
			this.placethingsatvertices.CheckedChanged += this.placethingsatvertices_CheckedChanged;
			this.reset.Click += this.reset_Click;
			this.showguidelines.CheckedChanged += this.showguidelines_CheckedChanged;
			this.radialdrawing.CheckedChanged += this.radialdrawing_CheckedChanged;
		}
	}
}
