// Generated by tools/port_toolstrip_ui.py from UDB's DrawLineOptionsPanel.Designer.cs: the toolbar items of the panel as Core item objects.
using System;
using System.Windows.Forms;
using CodeImp.DoomBuilder.Controls;

namespace CodeImp.DoomBuilder.BuilderModes
{
	internal partial class DrawLineOptionsPanel
	{
		private System.Windows.Forms.ToolStrip toolStrip1;
		private System.Windows.Forms.ToolStripButton continuousdrawing;
		private System.Windows.Forms.ToolStripButton autoclosedrawing;
		private System.Windows.Forms.ToolStripButton showguidelines;

		private void InitializeComponent()
		{
			this.toolStrip1 = new System.Windows.Forms.ToolStrip();
			this.continuousdrawing = new System.Windows.Forms.ToolStripButton();
			this.autoclosedrawing = new System.Windows.Forms.ToolStripButton();
			this.showguidelines = new System.Windows.Forms.ToolStripButton();
			this.toolStrip1.Name = "toolStrip1";
			this.toolStrip1.Text = "toolStrip1";
			this.continuousdrawing.CheckOnClick = true;
			this.continuousdrawing.Name = "continuousdrawing";
			this.continuousdrawing.Text = "Continuous drawing";
			this.continuousdrawing.Image = Properties.Resources.Repeat;
			this.autoclosedrawing.CheckOnClick = true;
			this.autoclosedrawing.Name = "autoclosedrawing";
			this.autoclosedrawing.Text = "Auto-finish drawing";
			this.autoclosedrawing.Image = Properties.Resources.NewSector2;
			this.showguidelines.CheckOnClick = true;
			this.showguidelines.Name = "showguidelines";
			this.showguidelines.Text = "Guidelines";
			this.showguidelines.Image = Properties.Resources.Guidelines;
			this.toolStrip1.Items.Add(this.continuousdrawing);
			this.toolStrip1.Items.Add(this.autoclosedrawing);
			this.toolStrip1.Items.Add(this.showguidelines);
			this.continuousdrawing.CheckedChanged += this.continuousdrawing_CheckedChanged;
			this.autoclosedrawing.CheckedChanged += this.autoclosedrawing_CheckedChanged;
			this.showguidelines.CheckedChanged += this.showguidelines_CheckedChanged;
		}
	}
}
