// Generated by tools/port_toolstrip_ui.py from UDB's DrawRectangleOptionsPanel.Designer.cs: the toolbar items of the panel as Core item objects.
using System;
using System.Windows.Forms;
using CodeImp.DoomBuilder.Controls;

namespace CodeImp.DoomBuilder.BuilderModes
{
	internal partial class DrawRectangleOptionsPanel
	{
		private System.Windows.Forms.ToolStrip toolStrip1;
		private System.Windows.Forms.ToolStripButton continuousdrawing;
		private System.Windows.Forms.ToolStripButton showguidelines;
		private System.Windows.Forms.ToolStripButton radialdrawing;
		private System.Windows.Forms.ToolStripButton placethingsatvertices;
		private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
		private System.Windows.Forms.ToolStripLabel radiuslabel;
		private CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown radius;
		private System.Windows.Forms.ToolStripLabel subdivslabel;
		private CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown subdivs;
		private System.Windows.Forms.ToolStripButton reset;

		private void InitializeComponent()
		{
			this.toolStrip1 = new System.Windows.Forms.ToolStrip();
			this.continuousdrawing = new System.Windows.Forms.ToolStripButton();
			this.showguidelines = new System.Windows.Forms.ToolStripButton();
			this.radialdrawing = new System.Windows.Forms.ToolStripButton();
			this.placethingsatvertices = new System.Windows.Forms.ToolStripButton();
			this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.radiuslabel = new System.Windows.Forms.ToolStripLabel();
			this.radius = new CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown();
			this.subdivslabel = new System.Windows.Forms.ToolStripLabel();
			this.subdivs = new CodeImp.DoomBuilder.Controls.ToolStripNumericUpDown();
			this.reset = new System.Windows.Forms.ToolStripButton();
			this.toolStrip1.Name = "toolStrip1";
			this.toolStrip1.Text = "toolStrip1";
			this.continuousdrawing.CheckOnClick = true;
			this.continuousdrawing.Name = "continuousdrawing";
			this.continuousdrawing.Text = "Continuous drawing";
			this.continuousdrawing.Image = Properties.Resources.Repeat;
			this.showguidelines.CheckOnClick = true;
			this.showguidelines.Name = "showguidelines";
			this.showguidelines.Text = "Guidelines";
			this.showguidelines.Image = Properties.Resources.Guidelines;
			this.radialdrawing.CheckOnClick = true;
			this.radialdrawing.Name = "radialdrawing";
			this.radialdrawing.Text = "Radial drawing";
			this.radialdrawing.Image = Properties.Resources.Radial;
			this.placethingsatvertices.CheckOnClick = true;
			this.placethingsatvertices.Name = "placethingsatvertices";
			this.placethingsatvertices.Text = "Place things";
			this.placethingsatvertices.Image = Properties.Resources.PlaceThings;
			this.toolStripSeparator1.Name = "toolStripSeparator1";
			this.radiuslabel.Name = "radiuslabel";
			this.radiuslabel.Text = "Bevel Radius:";
			this.radius.Maximum = 2048m;
			this.radius.Minimum = 0m;
			this.radius.Name = "radius";
			this.radius.Text = "0";
			this.radius.Value = 0m;
			this.subdivslabel.Name = "subdivslabel";
			this.subdivslabel.Text = "Subdivisions:";
			this.subdivs.Maximum = 128m;
			this.subdivs.Minimum = 0m;
			this.subdivs.Name = "subdivs";
			this.subdivs.Text = "0";
			this.subdivs.Value = 0m;
			this.reset.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.reset.Name = "reset";
			this.reset.Text = "Reset";
			this.reset.Image = Properties.Resources.Reset;
			this.toolStrip1.Items.Add(this.continuousdrawing);
			this.toolStrip1.Items.Add(this.showguidelines);
			this.toolStrip1.Items.Add(this.radialdrawing);
			this.toolStrip1.Items.Add(this.placethingsatvertices);
			this.toolStrip1.Items.Add(this.toolStripSeparator1);
			this.toolStrip1.Items.Add(this.radiuslabel);
			this.toolStrip1.Items.Add(this.radius);
			this.toolStrip1.Items.Add(this.subdivslabel);
			this.toolStrip1.Items.Add(this.subdivs);
			this.toolStrip1.Items.Add(this.reset);
			this.continuousdrawing.CheckedChanged += this.continuousdrawing_CheckedChanged;
			this.placethingsatvertices.CheckedChanged += this.placethingsatvertices_CheckedChanged;
			this.showguidelines.CheckedChanged += this.showguidelines_CheckedChanged;
			this.radialdrawing.CheckedChanged += this.radialdrawing_CheckedChanged;
			this.reset.Click += this.reset_Click;
		}
	}
}
