// Generated by tools/gen_resources.py from UDB Properties/Resources.resx: image resources loaded from embedded files.
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Reflection;

namespace CodeImp.DoomBuilder.AutomapMode.Properties
{
	internal static class Resources
	{
		private static Bitmap Load(string file)
		{
			string name = "CodeImp.DoomBuilder.AutomapMode.Resources." + file;
			using (Stream s = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
			{
				if (s == null) throw new FileNotFoundException("Embedded resource not found: " + name);
				return (Bitmap)Image.FromStream(s);
			}
		}

		public static Bitmap ShowSecrets => Load("ShowSecrets.png");
		public static Bitmap ShowHiddenLines => Load("ShowHiddenLines.png");
		public static Bitmap ShowLocks => Load("ShowLocks.png");
		public static Bitmap ShowTextures => Load("ShowTextures.png");

		/// <summary>Resource name (as in Properties.Resources.Name) to the embedded file under CodeImp.DoomBuilder.Resources.</summary>
		public static readonly Dictionary<string, string> Files = new Dictionary<string, string>(StringComparer.Ordinal)
		{
			["ShowSecrets"] = "ShowSecrets.png",
			["ShowHiddenLines"] = "ShowHiddenLines.png",
			["ShowLocks"] = "ShowLocks.png",
			["ShowTextures"] = "ShowTextures.png",
		};
	}
}
