// Generated by tools/gen_resources.py from UDB Properties/Resources.resx: image resources loaded from embedded files.
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Reflection;

namespace CodeImp.DoomBuilder.Plugins.VisplaneExplorer.Properties
{
	internal static class Resources
	{
		private static Bitmap Load(string file)
		{
			string name = "CodeImp.DoomBuilder.Plugins.VisplaneExplorer.Resources." + file;
			using (Stream s = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
			{
				if (s == null) throw new FileNotFoundException("Embedded resource not found: " + name);
				return (Bitmap)Image.FromStream(s);
			}
		}

		public static Bitmap Add => Load("Add.png");
		public static Bitmap Solidsegs => Load("Solidsegs.png");
		public static Bitmap Drawsegs => Load("Drawsegs.png");
		public static Bitmap Visplanes => Load("Visplanes.png");
		public static Bitmap Openings => Load("Openings.png");
		public static Bitmap Drawsegs_pal => Load("Drawsegs_pal.png");
		public static Bitmap Openings_pal => Load("Openings_pal.png");
		public static Bitmap Solidsegs_pal => Load("Solidsegs_pal.png");
		public static Bitmap Visplanes_pal => Load("Visplanes_pal.png");
		public static Bitmap Heatmap_pal => Load("Heatmap_pal.png");

		/// <summary>Resource name (as in Properties.Resources.Name) to the embedded file under CodeImp.DoomBuilder.Resources.</summary>
		public static readonly Dictionary<string, string> Files = new Dictionary<string, string>(StringComparer.Ordinal)
		{
			["Add"] = "Add.png",
			["Solidsegs"] = "Solidsegs.png",
			["Drawsegs"] = "Drawsegs.png",
			["Visplanes"] = "Visplanes.png",
			["Openings"] = "Openings.png",
			["Drawsegs_pal"] = "Drawsegs_pal.png",
			["Openings_pal"] = "Openings_pal.png",
			["Solidsegs_pal"] = "Solidsegs_pal.png",
			["Visplanes_pal"] = "Visplanes_pal.png",
			["Heatmap_pal"] = "Heatmap_pal.png",
		};
	}
}
