// Generated by tools/gen_resources.py from UDB Properties/Resources.resx: image resources loaded from embedded files.
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Reflection;

namespace CodeImp.DoomBuilder.TagRange.Properties
{
	internal static class Resources
	{
		private static Bitmap Load(string file)
		{
			string name = "CodeImp.DoomBuilder.TagRange.Resources." + file;
			using (Stream s = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
			{
				if (s == null) throw new FileNotFoundException("Embedded resource not found: " + name);
				return (Bitmap)Image.FromStream(s);
			}
		}

		public static Bitmap tag_blue => Load("tag_blue.png");

		/// <summary>Resource name (as in Properties.Resources.Name) to the embedded file under CodeImp.DoomBuilder.Resources.</summary>
		public static readonly Dictionary<string, string> Files = new Dictionary<string, string>(StringComparer.Ordinal)
		{
			["tag_blue"] = "tag_blue.png",
		};
	}
}
