#!/usr/bin/env python3
"""Regenerates a Properties/Resources.cs from UDB's Properties/Resources.resx (the Core's by default, or a plugin's).

The resx maps resource names (Properties.Resources.NewMap) to files in Resources/. This writes one Bitmap property per image
plus a name -> file map for UIs that load the PNG themselves (the Avalonia shell, without going through System.Drawing).
Usage (repo root): python3 tools/gen_resources.py <UDB Source/Core/Properties/Resources.resx>
  Plugin: python3 tools/gen_resources.py <resx> src/Plugins/BuilderModes/Properties/Resources.cs CodeImp.DoomBuilder.BuilderModes
  (the embedded files are then "<namespace>.Resources.<file>", as MSBuild names the project's Resources folder)
"""
import re, sys
OUT = sys.argv[2] if len(sys.argv) > 2 else 'src/DoomBuilder.Core/Properties/Resources.cs'
NS = sys.argv[3] if len(sys.argv) > 3 else 'CodeImp.DoomBuilder'
res = open(sys.argv[1], encoding='utf-8-sig').read()
items = re.findall(r'<data name="([^"]+)" type="System.Resources.ResXFileRef[^"]*">\s*<value>([^;<]+);([^<]*)</value>', res)
out = ['// Generated by tools/gen_resources.py from UDB Properties/Resources.resx: image resources loaded from embedded files.',
       'using System;', 'using System.Collections.Generic;', 'using System.Drawing;', 'using System.IO;', 'using System.Reflection;', '',
       'namespace ' + NS + '.Properties', '{', '\tinternal static class Resources', '\t{',
       '\t\tprivate static Bitmap Load(string file)', '\t\t{',
       '\t\t\tstring name = "' + NS + '.Resources." + file;',
       '\t\t\tusing (Stream s = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))', '\t\t\t{',
       '\t\t\t\tif (s == null) throw new FileNotFoundException("Embedded resource not found: " + name);',
       '\t\t\t\treturn (Bitmap)Image.FromStream(s);', '\t\t\t}', '\t\t}', '']
files = []
for name, path, typ in items:
    f = path.replace('\\', '/').split('/')[-1]
    if not f.lower().endswith(('.png', '.gif', '.bmp', '.jpg')): continue
    ident = re.sub(r'\W', '_', name)
    out.append(f'\t\tpublic static Bitmap {ident} => Load("{f}");')
    files.append((ident, f))
out += ['', '\t\t/// <summary>Resource name (as in Properties.Resources.Name) to the embedded file under CodeImp.DoomBuilder.Resources.</summary>',
        '\t\tpublic static readonly Dictionary<string, string> Files = new Dictionary<string, string>(StringComparer.Ordinal)', '\t\t{']
out += [f'\t\t\t["{i}"] = "{f}",' for i, f in files]
out += ['\t\t};', '\t}', '}']
open(OUT, 'w').write('\n'.join(out) + '\n')
print(len(files), 'images')
