#!/usr/bin/env python3
"""Ports a UDB WinForms panel/form made of ToolStrip items to the Core's item model (Compat/ToolStripItems.cs).

The designer file lists the items (`this.x = new ToolStripButton()`), their properties and event hookups. This writes a
partial class with the same fields and an InitializeComponent that builds the same items, so the original logic file keeps
working unchanged. The logic file is copied with its WinForms base class removed.

Usage (repo root):
    python3 tools/port_toolstrip_ui.py <UDB Interface dir> <ClassName> <out dir> [--keep-base]
Writes <out>/<ClassName>.cs (logic) and <out>/<ClassName>.Designer.cs (generated).
"""
import re, sys, os

src_dir, cls, out_dir = sys.argv[1], sys.argv[2], sys.argv[3]
design = open(os.path.join(src_dir, cls + '.Designer.cs'), encoding='utf-8-sig').read()
logic = open(os.path.join(src_dir, cls + '.cs'), encoding='utf-8-sig').read()

# strings the designer reads from the form's .resx (resources.GetString("name.Property"))
resx = {}
resx_path = os.path.join(src_dir, cls + '.resx')
if os.path.exists(resx_path):
    import xml.etree.ElementTree as ET
    for d in ET.parse(resx_path).getroot().iter('data'):
        v = d.find('value')
        if v is not None and d.get('type') is None: resx[d.get('name')] = v.text or ''

def cs_string(text):
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"').replace('\r', '').replace('\n', '\\n') + '"'

ITEM_TYPES = {'ToolStripButton', 'ToolStripActionButton', 'ToolStripNumericUpDown', 'ToolStripCheckBox', 'ToolStripLabel',
              'ToolStripSeparator', 'ToolStripComboBox', 'ToolStripMenuItem', 'ToolStripDropDownButton', 'ToolStripSplitButton',
              'ToolStrip', 'MenuStrip'}

# ---- fields: name -> (full type as written, short type)
fields = {}
for m in re.finditer(r'this\.(\w+) = new ([\w.]+)\(', design):
    short = m.group(2).split('.')[-1]
    if short in ITEM_TYPES: fields[m.group(1)] = m.group(2)
order = list(fields)

def csharp_decimal(txt):
    m = re.match(r'new decimal\(new int\[\] \{\s*([-\d]+),\s*([-\d]+),\s*([-\d]+),\s*([-\dx]+)\}\)', txt.strip(), re.S)
    if not m: return txt.strip()
    lo, mid, hi, flags = m.groups()
    flags = int(flags, 0) if flags.startswith(('0x','-')) or flags.isdigit() else 0
    value = int(lo) + (int(mid) << 32) + (int(hi) << 64)
    if flags & 0x80000000 or flags < 0: value = -value
    return str(value) + 'm'

body = []
props = {}
for m in re.finditer(r'this\.(\w+)\.(Text|ToolTipText|Name|Tag|CheckOnClick|Checked|Enabled|Visible|DisplayStyle|Minimum|Maximum|Value|Increment|ShortcutKeyDisplayString)\s*=\s*(.*?);\s*$', design, re.M | re.S):
    name, prop, value = m.groups()
    if name not in fields: continue
    # a multi-line `new decimal(new int[] {...})` is captured lazily up to the first ';' at line end: re-read to the closing )
    if value.startswith('new decimal'):
        end = design.index(');', m.start(3)) + 1
        value = design[m.start(3):end]
        value = csharp_decimal(value)
    value = value.strip()
    g = re.match(r'resources\.GetString\("([^"]+)"\)', value)
    if g:
        if g.group(1) not in resx: continue
        value = cs_string(resx[g.group(1)])
    props.setdefault(name, []).append((prop, value))
for m in re.finditer(r'this\.(\w+)\.Image = (?:global::)?[\w.]*?Properties\.Resources\.(\w+);', design):
    if m.group(1) in fields: props.setdefault(m.group(1), []).append(('Image', 'Properties.Resources.' + m.group(2)))

events = []
for m in re.finditer(r'this\.(\w+)\.(\w+) \+= new (?:System\.)?(?:EventHandler|[\w.]+)\(this\.(\w+)\);', design):
    if m.group(1) in fields: events.append((m.group(1), m.group(2), m.group(3)))

containers = []
for m in re.finditer(r'this\.(\w+)\.(Items|DropDownItems)\.AddRange\(new (?:System\.Windows\.Forms\.)?ToolStripItem\[\] \{(.*?)\}\);', design, re.S):
    if m.group(1) in fields: containers.append((m.group(1), m.group(2), re.findall(r'this\.(\w+)', m.group(3))))

# ---- emit the designer part
ns = re.search(r'namespace ([\w.]+)', design).group(1)
vis = 'public' if re.search(r'public\s+partial\s+class\s+%s' % cls, logic) else 'internal'   # same as the logic part
out = ['// Generated by tools/port_toolstrip_ui.py from UDB\'s %s.Designer.cs: the toolbar items of the panel as Core item objects.' % cls,
       'using System;', 'using System.Windows.Forms;', 'using CodeImp.DoomBuilder.Controls;', '', 'namespace ' + ns, '{',
       '\t%s partial class %s' % (vis, cls), '\t{']
for n in order:
    out.append('\t\tprivate %s %s;' % (fields[n], n))
out += ['', '\t\tprivate void InitializeComponent()', '\t\t{']
for n in order:
    out.append('\t\t\tthis.%s = new %s();' % (n, fields[n]))
for n in order:
    for prop, value in props.get(n, []):
        out.append('\t\t\tthis.%s.%s = %s;' % (n, prop, value))
for host, kind, kids in containers:
    for k in kids:
        out.append('\t\t\tthis.%s.%s.Add(this.%s);' % (host, kind, k))
for n, ev, handler in events:
    out.append('\t\t\tthis.%s.%s += this.%s;' % (n, ev, handler))
out += ['\t\t}', '\t}', '}']
open(os.path.join(out_dir, cls + '.Designer.cs'), 'w').write('\n'.join(out) + '\n')

# ---- the logic part: same file, without the WinForms base class
logic = re.sub(r'(partial class %s)\s*:\s*\w+' % cls, r'\1 : CodeImp.DoomBuilder.Controls.ToolStripHost', logic)
logic = re.sub(r'\bprivate\s+bool\s+blockevents', 'private bool blockevents', logic)
open(os.path.join(out_dir, cls + '.cs'), 'w').write(logic)
print(cls, len(order), 'items', len(events), 'events')
